import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createElement } from 'react';
import { act, create, type ReactTestRenderer } from 'react-test-renderer';
import { transformWithOxc } from 'vite';
import { indexedDB } from 'fake-indexeddb';
import { NetworkD1, seedNetwork, networkOsm } from './helpers/networkD1.ts';
import { prepareAreaTasks } from '../worker/areaTaskPreparation.ts';
import { loadCampaignSnapshot } from '../worker/campaignRepository.ts';
import { queuedNetworkIntents } from '../src/data/networkIntentQueue.ts';

test('real React Smart Mark hook chooses Area from A/B, previews and queues offline, then accepts another Area',async(t)=>{
  const db=new NetworkD1(true);seedNetwork(db);
  await prepareAreaTasks(db,'campaign_n','area_n',{fetchImpl:async()=>networkOsm()});
  const snapshot=(await loadCampaignSnapshot(db,'campaign_n'))!;
  const road=snapshot.tasks[0];
  snapshot.areas.push({...snapshot.areas[0],id:'area_second'});
  snapshot.tasks.push({...road,id:'street_second',areaId:'area_second',geometry:{type:'LineString',coordinates:road.geometry.coordinates.map(([x,y])=>[x,y+0.02])}});
  const sourceUrl=new URL('../src/map/useNetworkWorkspace.tsx',import.meta.url);
  const transformed=await transformWithOxc(await readFile(sourceUrl,'utf8'),sourceUrl.pathname,{jsx:{runtime:'automatic'}});
  const code=transformed.code.replace(/from\s*(['"])([^'"]+)\1/g,(_all,quote,specifier)=>`from ${quote}${specifier.startsWith('.')?new URL(specifier,sourceUrl).href:import.meta.resolve(specifier)}${quote}`);
  const {useNetworkWorkspace}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
  const originals=new Map<string,PropertyDescriptor|undefined>();
  const set=(name:string,value:unknown)=>{originals.set(name,Object.getOwnPropertyDescriptor(globalThis,name));Object.defineProperty(globalThis,name,{value,configurable:true,writable:true});};
  const events=new EventTarget();
  set('window',{setInterval,clearInterval,setTimeout,clearTimeout,addEventListener:events.addEventListener.bind(events),removeEventListener:events.removeEventListener.bind(events)});
  set('navigator',{onLine:false});set('indexedDB',indexedDB);set('IS_REACT_ACT_ENVIRONMENT',true);
  set('fetch',async()=>Response.json({status:'ready',updatedAt:'2026-09-09T00:00:00Z'}));
  let renderer:ReactTestRenderer|undefined;let workspace:any;
  t.after(async()=>{if(renderer)await act(async()=>renderer!.unmount());for(const [key,descriptor]of originals){if(descriptor)Object.defineProperty(globalThis,key,descriptor);else Reflect.deleteProperty(globalThis,key);}db.sqlite.close();});
  function Harness(){workspace=useNetworkWorkspace(snapshot,{role:'admin',teamId:null},async()=>{},()=>true);return workspace.panel;}
  await act(async()=>{renderer=create(createElement(Harness));});
  await act(async()=>workspace.open(null));
  assert.equal(workspace.active,true);
  await act(async()=>workspace.mapProps.onSmartStreetPoint(road.geometry.coordinates[0],[road.id]));
  assert.equal(workspace.mapProps.smartStartAnchor.sourceId,road.id);
  await act(async()=>workspace.mapProps.onSmartStreetPoint(road.geometry.coordinates.at(-1),[road.id]));
  assert.ok(workspace.mapProps.smartPreviewGeometry);
  const complete=renderer!.root.findAllByType('button').find(button=>button.children.includes('Erledigt'))!;
  assert.equal(complete.props.disabled,false);
  await act(async()=>{complete.props.onClick();await new Promise(resolve=>setTimeout(resolve,30));});
  const queued=await queuedNetworkIntents('campaign_n:admin::');
  assert.equal(queued.length,1);assert.equal(queued[0].intent.areaId,'area_n');
  assert.equal(workspace.mapProps.smartStartAnchor,null);
  const second=snapshot.tasks.at(-1)!;
  await act(async()=>workspace.mapProps.onSmartStreetPoint(second.geometry.coordinates[0],[second.id]));
  assert.equal(workspace.mapProps.smartStartAnchor.sourceId,second.id);
});
