import { useEffect, useRef, useState } from "react";
import { GeolocateControl, Map, NavigationControl } from "maplibre-gl";
import type { StyleSpecification } from "maplibre-gl";
import type { Area, DistributionTask, LngLat, MapCameraView } from "../domain/campaign";
import type { Language } from "../i18n";
import { t } from "../i18n";
import { loadPersonalMapView, savePersonalMapView } from "./cameraStore";
import "maplibre-gl/dist/maplibre-gl.css";

type MapMode = "browse" | "draw" | "edit" | "street-draw";
type RenderArea = Area & { color: string };
type RenderTask = DistributionTask & { color: string };
export type MapRefreshState = "idle" | "loading" | "current" | "error" | "available";
export type MapCameraCommand = { id: number; view: MapCameraView; persist?: boolean } | null;

type MapViewProps = {
  campaignId: string; campaignDefaultView: MapCameraView | null; language: Language; areas: RenderArea[]; tasks: RenderTask[]; selectedTaskId: string | null; mode: MapMode; draftVertices: LngLat[]; draftColor: string; editingVertices: LngLat[]; editingColor: string; selectedVertexIndex: number | null; streetDraftVertices: LngLat[]; streetDraftColor: string; refreshState: MapRefreshState; cameraCommand: MapCameraCommand; onCameraChange: (camera: MapCameraView) => void; onRefresh: () => void; onAreaSelect: (areaId: string | null) => void; onTaskSelect: (taskId: string | null) => void; onDrawPoint: (point: LngLat) => void; onEditVertexSelect: (index: number) => void; onEditVertexMove: (index: number, point: LngLat) => void; onStreetDrawPoint: (point: LngLat) => void;
};
const GERMANY_VIEW: MapCameraView = { center: [10.45, 51.16], zoom: 5.3, bearing: 0 };
const CARTO_VOYAGER_RETINA_STYLE: StyleSpecification = { version: 8, sources: { carto: { type: "raster", tiles: ["https://a.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}@2x.png", "https://b.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}@2x.png", "https://c.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}@2x.png", "https://d.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}@2x.png"], tileSize: 256, minzoom: 0, maxzoom: 20, attribution: '<a href="https://www.openstreetmap.org/copyright" target="_blank">© OpenStreetMap contributors</a> · <a href="https://carto.com/attributions" target="_blank">© CARTO</a>' } }, layers: [{ id: "map-background", type: "background", paint: { "background-color": "#fbf8f3" } }, { id: "carto-basemap", type: "raster", source: "carto", minzoom: 0, maxzoom: 20, paint: { "raster-fade-duration": 0 } }] };
function samePoint(a: LngLat, b: LngLat) { return a[0] === b[0] && a[1] === b[1]; }
function openAreaRing(area: RenderArea): LngLat[] { const ring = area.geometry.coordinates[0] as LngLat[]; return ring.length > 1 && samePoint(ring[0], ring[ring.length - 1]) ? ring.slice(0, -1) : ring; }
function pointInPolygon(point: LngLat, polygon: LngLat[]) { if (polygon.length < 3) return false; let inside = false; const [x, y] = point; for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i, i += 1) { const [xi, yi] = polygon[i]; const [xj, yj] = polygon[j]; if (yi > y !== yj > y) { const boundaryX = ((xj - xi) * (y - yi)) / (yj - yi) + xi; if (x < boundaryX) inside = !inside; } } return inside; }
function pointToSegmentDistance(point: {x:number;y:number}, start:{x:number;y:number}, end:{x:number;y:number}) { const dx=end.x-start.x, dy=end.y-start.y; if(dx===0&&dy===0)return Math.hypot(point.x-start.x,point.y-start.y); const factor=Math.max(0,Math.min(1,((point.x-start.x)*dx+(point.y-start.y)*dy)/(dx*dx+dy*dy))); return Math.hypot(point.x-(start.x+factor*dx),point.y-(start.y+factor*dy)); }
function taskHitDistance(map:Map,task:RenderTask,point:{x:number;y:number}){const coordinates=task.geometry.coordinates as LngLat[];let best=Infinity;for(let i=1;i<coordinates.length;i++)best=Math.min(best,pointToSegmentDistance(point,map.project(coordinates[i-1]),map.project(coordinates[i])));return best;}
function findTaskHit(map:Map,tasks:RenderTask[],point:{x:number;y:number}){let hitId:string|null=null,best=16;for(const task of tasks){const distance=taskHitDistance(map,task,point);if(distance<=best){hitId=task.id;best=distance;}}return hitId;}
function findEditVertex(map:Map,vertices:LngLat[],point:{x:number;y:number}){let hit:number|null=null,best=24;for(let i=0;i<vertices.length;i++){const projected=map.project(vertices[i]);const distance=Math.hypot(projected.x-point.x,projected.y-point.y);if(distance<=best){hit=i;best=distance;}}return hit;}
function statusPresentation(status:DistributionTask["status"]){switch(status){case"completed":return{width:4,opacity:.48,dash:undefined as string|undefined};case"later":return{width:6,opacity:.88,dash:"12 8"};case"not-deliverable":return{width:5.5,opacity:.8,dash:"3 7"};default:return{width:6,opacity:1,dash:undefined as string|undefined};}}
function projectedPoints(map:Map|null,coordinates:LngLat[]){if(!map)return"";return coordinates.map(c=>{const p=map.project(c);return `${p.x},${p.y}`;}).join(" ");}
function cameraFromMap(map:Map):MapCameraView{const c=map.getCenter();return{center:[c.lng,c.lat],zoom:map.getZoom(),bearing:map.getBearing()};}
function ProjectedMarkers({map,coordinates,color,selectedIndex=null,radius=8}:{map:Map|null;coordinates:LngLat[];color:string;selectedIndex?:number|null;radius?:number}){if(!map)return null;return coordinates.map((coordinate,index)=>{const point=map.project(coordinate);const selected=selectedIndex===index;return <circle key={`${coordinate[0]}:${coordinate[1]}:${index}`} cx={point.x} cy={point.y} r={selected?radius+3:radius} fill={selected?"#ffffff":color} stroke={selected?color:"#ffffff"} strokeWidth={selected?4.5:3.5} vectorEffect="non-scaling-stroke"/>;});}
export function MapView({campaignId,campaignDefaultView,language,areas,tasks,selectedTaskId,mode,draftVertices,draftColor,editingVertices,editingColor,selectedVertexIndex,streetDraftVertices,streetDraftColor,refreshState,cameraCommand,onCameraChange,onRefresh,onAreaSelect,onTaskSelect,onDrawPoint,onEditVertexSelect,onEditVertexMove,onStreetDrawPoint}:MapViewProps){
const containerRef=useRef<HTMLDivElement>(null);const mapRef=useRef<Map|null>(null);const cameraSaveTimerRef=useRef<number|null>(null);const suppressNextCameraSaveRef=useRef(false);const[error,setError]=useState<string|null>(null);const[,forceOverlayRender]=useState(0);
const interactionRef=useRef({areas,tasks,mode,editingVertices,selectedVertexIndex,onAreaSelect,onTaskSelect,onDrawPoint,onEditVertexSelect,onEditVertexMove,onStreetDrawPoint});
useEffect(()=>{interactionRef.current={areas,tasks,mode,editingVertices,selectedVertexIndex,onAreaSelect,onTaskSelect,onDrawPoint,onEditVertexSelect,onEditVertexMove,onStreetDrawPoint};},[areas,tasks,mode,editingVertices,selectedVertexIndex,onAreaSelect,onTaskSelect,onDrawPoint,onEditVertexSelect,onEditVertexMove,onStreetDrawPoint]);
useEffect(()=>{if(!containerRef.current||mapRef.current)return;let active=true;const initialCamera=loadPersonalMapView(campaignId)??campaignDefaultView??GERMANY_VIEW;try{const map=new Map({container:containerRef.current,style:CARTO_VOYAGER_RETINA_STYLE,center:initialCamera.center,zoom:initialCamera.zoom,bearing:initialCamera.bearing,maxZoom:20,renderWorldCopies:false,cancelPendingTileRequestsWhileZooming:false,validateStyle:import.meta.env.DEV});mapRef.current=map;const redraw=()=>{if(active)forceOverlayRender(v=>v+1);};const persistCamera=()=>{if(suppressNextCameraSaveRef.current){suppressNextCameraSaveRef.current=false;onCameraChange(cameraFromMap(map));return;}if(cameraSaveTimerRef.current!==null)window.clearTimeout(cameraSaveTimerRef.current);cameraSaveTimerRef.current=window.setTimeout(()=>{const camera=cameraFromMap(map);savePersonalMapView(campaignId,camera);onCameraChange(camera);},350);};map.on("load",redraw);map.on("move",redraw);map.on("rotate",redraw);map.on("zoom",redraw);map.on("resize",redraw);map.on("moveend",persistCamera);map.on("click",event=>{const interaction=interactionRef.current;const lngLat:LngLat=[event.lngLat.lng,event.lngLat.lat];if(interaction.mode==="draw"){interaction.onDrawPoint(lngLat);return;}if(interaction.mode==="street-draw"){interaction.onStreetDrawPoint(lngLat);return;}if(interaction.mode==="edit"){const vertexIndex=findEditVertex(map,interaction.editingVertices,event.point);if(vertexIndex!==null){interaction.onEditVertexSelect(vertexIndex);return;}if(interaction.selectedVertexIndex!==null)interaction.onEditVertexMove(interaction.selectedVertexIndex,lngLat);return;}const taskId=findTaskHit(map,interaction.tasks,event.point);if(taskId){interaction.onTaskSelect(taskId);return;}interaction.onTaskSelect(null);const areaHit=[...interaction.areas].reverse().find(area=>pointInPolygon(lngLat,openAreaRing(area)));interaction.onAreaSelect(areaHit?.id??null);});map.addControl(new NavigationControl({showCompass:true,showZoom:true}),"top-right");map.addControl(new GeolocateControl({positionOptions:{enableHighAccuracy:true},trackUserLocation:false,showUserLocation:true,showAccuracyCircle:true}),"top-right");onCameraChange(initialCamera);redraw();}catch(cause){console.error("Map initialization failed",cause);if(active)setError(t(language,"mapInitError"));}return()=>{active=false;if(cameraSaveTimerRef.current!==null)window.clearTimeout(cameraSaveTimerRef.current);mapRef.current?.remove();mapRef.current=null;};},[campaignId]);
useEffect(()=>{const map=mapRef.current;if(!map)return;if(mode==="browse")map.doubleClickZoom.enable();else map.doubleClickZoom.disable();},[mode]);
useEffect(()=>{const map=mapRef.current;if(!map||!cameraCommand)return;if(cameraCommand.persist===false)suppressNextCameraSaveRef.current=true;map.jumpTo({center:cameraCommand.view.center,zoom:cameraCommand.view.zoom,bearing:cameraCommand.view.bearing});},[cameraCommand?.id]);
const map=mapRef.current,width=containerRef.current?.clientWidth??1,height=containerRef.current?.clientHeight??1;const refreshText=refreshState==="loading"?t(language,"refreshLoading"):refreshState==="error"?t(language,"refreshError"):refreshState==="available"?t(language,"newData"):refreshState==="current"?t(language,"refreshCurrent"):"";
return <section className={`map-region map-mode-${mode}`} aria-label={t(language,"map")}><div ref={containerRef} className="map"/><svg className="application-overlay" viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" aria-hidden="true">
{areas.map(area=><polygon key={area.id} points={projectedPoints(map,openAreaRing(area))} fill={area.color} fillOpacity={0.24} stroke={area.color} strokeWidth={4} strokeLinejoin="round" vectorEffect="non-scaling-stroke"/>)}
{tasks.map(task=>{const points=projectedPoints(map,task.geometry.coordinates as LngLat[]);const p=statusPresentation(task.status);const selected=task.id===selectedTaskId;return <g key={task.id}>{selected?<polyline points={points} fill="none" stroke="#172019" strokeWidth={15} strokeLinecap="round" strokeLinejoin="round" opacity={0.9} vectorEffect="non-scaling-stroke"/>:null}<polyline points={points} fill="none" stroke="#ffffff" strokeWidth={10} strokeLinecap="round" strokeLinejoin="round" opacity={0.98} vectorEffect="non-scaling-stroke"/><polyline points={points} fill="none" stroke={task.color} strokeWidth={p.width} strokeDasharray={p.dash} strokeLinecap="round" strokeLinejoin="round" opacity={p.opacity} vectorEffect="non-scaling-stroke"/></g>;})}
{mode==="draw"?<>{draftVertices.length>=2?(draftVertices.length>=3?<polygon points={projectedPoints(map,draftVertices)} fill={draftColor} fillOpacity={0.3} stroke={draftColor} strokeWidth={6} strokeLinejoin="round" vectorEffect="non-scaling-stroke"/>:<polyline points={projectedPoints(map,draftVertices)} fill="none" stroke={draftColor} strokeWidth={6} strokeLinecap="round" vectorEffect="non-scaling-stroke"/>):null}<ProjectedMarkers map={map} coordinates={draftVertices} color={draftColor} radius={9}/></>:null}
{mode==="edit"?<>{editingVertices.length>=3?<><polygon points={projectedPoints(map,editingVertices)} fill="none" stroke="#ffffff" strokeWidth={13} strokeLinejoin="round" vectorEffect="non-scaling-stroke"/><polygon points={projectedPoints(map,editingVertices)} fill={editingColor} fillOpacity={0.32} stroke={editingColor} strokeWidth={7} strokeLinejoin="round" vectorEffect="non-scaling-stroke"/></>:null}<ProjectedMarkers map={map} coordinates={editingVertices} color={editingColor} selectedIndex={selectedVertexIndex} radius={10}/></>:null}
{mode==="street-draw"?<>{streetDraftVertices.length>=2?<><polyline points={projectedPoints(map,streetDraftVertices)} fill="none" stroke="#ffffff" strokeWidth={11} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke"/><polyline points={projectedPoints(map,streetDraftVertices)} fill="none" stroke={streetDraftColor} strokeWidth={7} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke"/></>:null}<ProjectedMarkers map={map} coordinates={streetDraftVertices} color={streetDraftColor} radius={9}/></>:null}</svg><div className="map-refresh-control"><button className="map-refresh-button" type="button" onClick={onRefresh} disabled={refreshState==="loading"} aria-label={t(language,"refreshData")} title={t(language,"refreshData")}>↻</button>{refreshText?<span className={`map-refresh-feedback is-${refreshState}`}>{refreshText}</span>:null}</div>{error?<div className="map-error">{error}</div>:null}</section>;
}
